### ISSUE TITLE
Změna sloupců v deníku

### ISSUE THREAD

**Issue by djha53k** [ladislav-filip/Denik-IG#4]
Cena > Nákupní cena
Cena teď > Aktuální cena
Množství > Počet kusů
Cena celkem > Nákupní cena
Cena celkem teď > Tržní cena

Vytvořeno > Datum nákupu (jako prvni sloupec)

Zisk a Zisk [%] ponechat jak jsou.

**Comment by ladislav-filip** [comment]
Přejmenováno.
Pouze sloupec Vytvořeno musí zůstat, protože to není datum nákupu, ale datum, kdy byl záznam vložen do databáze.
Informaci o datu nákupu nejprve musíme doplnit.
